language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - name: "php 7.0 (install) - unit"
      php: 7.0
      env:
        - DEPS=NO
        - LEVEL=UNIT
    - name: "php 7.0 (update) - unit"
      php: 7.0
      env:
        - DEPS=HIGH
        - LEVEL=UNIT
    - name: "php 7.0 (update) - integration"
      php: 7.0
      env:
        - DEPS=HIGH
        - LEVEL=INTEGRATION
    - name: "php 7.1 (install) - unit"
      php: 7.1
      env:
        - DEPS=NO
        - LEVEL=UNIT
    - name: "php 7.1 (update) - unit"
      php: 7.1
      env:
        - DEPS=HIGH
        - LEVEL=UNIT
    - name: "php 7.2 (install) - unit"
      php: 7.2
      env:
        - DEPS=NO
        - LEVEL=UNIT
    - name: "php 7.2 (update) - unit"
      php: 7.2
      env:
        - DEPS=HIGH
        - LEVEL=UNIT
    - name: "php 7.3 (install) - unit"
      php: 7.3
      env:
        - DEPS=NO
        - LEVEL=UNIT
    - name: "php 7.3 (update) - unit"
      php: 7.3
      env:
        - DEPS=HIGH
        - LEVEL=UNIT
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
before_install:
    - ./test/script/travis_before_install.sh
install:
    - ./test/script/travis_install.sh
script:
    - ./test/script/travis_script.sh
after_success:
    - php vendor/bin/codacycoverage clover build/coverage/xml
